In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url='https://www.cartrade.com/new-cars/best-electric-cars-in-india/'

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')
vehicle_links = soup.find_all('a', class_='font-19 font-valhalla color-scarlet')

In [3]:
dict_info={'Title':[],'Hyperlink':[],'Type':'Cars'}
for link in vehicle_links:
    dict_info['Title'].append(link.get_text())  # Get the title
    dict_info['Hyperlink'].append('https://www.cartrade.com/'+link['href'])  # Get the hyperlink

In [4]:
import pandas as pd

In [5]:
df=pd.DataFrame(dict_info)
df.head()

           Title                                      Hyperlink  Type
0  Tata Punch EV  https://www.cartrade.com//tata-cars/punch-ev/  Cars
1    MG Comet EV    https://www.cartrade.com//mg-cars/comet-ev/  Cars
2  Tata Nexon EV  https://www.cartrade.com//tata-cars/nexon-ev/  Cars
3  Tata Tiago EV  https://www.cartrade.com//tata-cars/tiago-ev/  Cars
4       BYD Seal       https://www.cartrade.com//byd-cars/seal/  Cars

In [6]:
df1=pd.read_csv('Vehicle info/EV_India.csv')

In [7]:
df1

,Sr. No.,State Name,Total Electric Vehicle,Total Non-Electric Vehicle,Total
0,1,Andaman & Nicobar Island,162,"1,46,945","1,47,107"
1,2,Andra Pradesh,NaN,NaN,NaN
2,3,Arunachal Pradesh,20,"2,52,965","2,52,985"
3,4,Assam,64766,"46,77,053","47,41,819"
4,5,Bihar,83335,"1,04,07,078","1,04,90,413"
5,6,Chandigarh,2812,"7,46,881","7,49,693"
6,7,Chhattisgarh,20966,"68,36,200","68,57,166"
7,8,Delhi,"1,56,393","76,85,600","78,41,993"
8,9,Goa,3870,"10,71,570","10,75,440"
9,10,Gujarat,45272,"2,06,05,484","2,06,50,756"
10,11,Haryana,37035,"1,07,78,270","1,08,15,305"
11,12,Himachal Pradesh,1175,"19,64,754","19,65,929"
12,13,Jammu and Kashmir,2941,"18,69,962","18,72,903"
13,14,Jharkhand,16811,"64,86,937","65,03,748"
14,15,Karnataka,"1,20,532","2,68,70,303","2,69,90,835"
15,16,Kerala,30775,"1,57,74,078","1,58,04,853"
16,17,Ladakh,26,38302,38328
17,18,Lakshadweep,NaN,NaN,NaN
18,19,Madhya Pradesh,NaN,NaN,NaN
19,20,Maharashtra,"1,16,646","3,10,58,990","3,11,75,636"
20,21,Manipur,586,"4,99,324","4,99,910"
21,22,Meghalaya,49,"4,59,001","4,59,050"
22,23,Mizoram,21,"3,15,626","3,15,647"
23,24,Nagaland,58,"3,39,129","3,39,187"
24,25,Odisha,23371,"98,45,073","98,68,444"
25,26,Puducherry,2149,"12,13,735","12,15,884"
26,27,Punjab,14804,"1,24,63,019","1,24,77,823"
27,28,Rajasthan,81338,"1,73,27,388","1,74,08,726"
28,29,Sikkim,21,97189,97210
29,30,Tamil Nadu,82051,"2,98,42,376","2,99,24,427"
30,31,Telangana,NaN,NaN,NaN
31,32,Tripura,9262,"6,50,026","6,59,288"
32,33,UT of DNH and DD,183,"3,07,671","3,07,854"
33,34,Uttarakhand,31008,"33,12,041","33,43,049"
34,35,Uttar Pradesh,"3,37,180","4,00,92,490","4,04,29,670"
35,36,West Bengal,48767,"1,41,34,171","1,41,82,938"

In [8]:
df2=pd.read_csv('Vehicle info/Electric_Vehicle_Population_Data.csv')
df2

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WAUTPBFF4H,King,Seattle,WA,98126.0,2017,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16,0,34.0,235085336,POINT (-122.374105 47.54468),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,WAUUPBFF2J,Thurston,Olympia,WA,98502.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16,0,22.0,237896795,POINT (-122.943445 47.059252),PUGET SOUND ENERGY INC,5.306701e+10
2,5YJSA1E22H,Thurston,Lacey,WA,98516.0,2017,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,22.0,154498865,POINT (-122.78083 47.083975),PUGET SOUND ENERGY INC,5.306701e+10
3,1C4JJXP62M,Thurston,Tenino,WA,98589.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,20.0,154525493,POINT (-122.85403 46.856085),PUGET SOUND ENERGY INC,5.306701e+10
4,5YJ3E1EC9L,Yakima,Yakima,WA,98902.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308,0,14.0,225996361,POINT (-120.524012 46.5973939),PACIFICORP,5.307700e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181453,50EA1TEA7P,Douglas,East Wenatchee,WA,98802.0,2023,LUCID,AIR,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,12.0,244207316,POINT (-120.28674 47.4176),PUD NO 1 OF DOUGLAS COUNTY,5.301795e+10
181454,1C4JJXP60N,Spokane,Spokane Valley,WA,99206.0,2022,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,4.0,207180774,POINT (-117.24549 47.6534),BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||...,5.306301e+10
181455,5YJ3E1EA0M,King,Enumclaw,WA,98022.0,2021,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,31.0,161934202,POINT (-121.98953 47.20347),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
181456,5YJ3E1EC8L,Clark,Vancouver,WA,98682.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308,0,18.0,100859650,POINT (-122.5286031 45.6686601),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
181457,5YJSA1E27F,Whatcom,Bellingham,WA,98225.0,2015,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208,0,42.0,256731576,POINT (-122.486115 48.761615),PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM CO...,5.307300e+10

In [9]:
df3=pd.read_csv('Vehicle info/RS_Session_256_AU_95_C (1).csv')
df3

,State Name,Two Wheeler,Three Wheeler,Four Wheeler,Goods Vehicles,Public Service Vehicle,Special Category Vehicles,Ambulance/Hearses,Construction Equipment Vehicle,Other,Grand Total
0,Andaman and Nicobar Island,1,30.0,81,NaN,40.0,NaN,NaN,NaN,7.0,159
1,Arunachal Pradesh,14,NaN,5,NaN,NaN,NaN,NaN,NaN,1.0,20
2,Assam,721,47041.0,161,7.0,15.0,NaN,NaN,NaN,2.0,47947
3,Bihar,5003,59079.0,114,11.0,26.0,NaN,NaN,NaN,8.0,64241
4,Chandigarh,298,1410.0,182,NaN,40.0,NaN,NaN,NaN,1.0,1931
5,Chhattisgarh,6424,5341.0,117,1077.0,1.0,NaN,NaN,368.0,100.0,13428
6,Delhi,14730,112831.0,3051,49.0,39.0,NaN,NaN,NaN,1602.0,132302
7,Goa,1314,28.0,289,13.0,36.0,2.0,NaN,NaN,4.0,1686
8,Gujarat,13662,1869.0,1309,28.0,278.0,344.0,NaN,26.0,77.0,17593
9,Haryana,7777,18595.0,186,122.0,8.0,2.0,NaN,NaN,90.0,26780
10,Himachal Pradesh,368,167.0,37,7.0,86.0,NaN,NaN,NaN,46.0,711
11,Jammu and Kashmir,1417,43.0,10,6.0,43.0,NaN,NaN,NaN,8.0,1527
12,Jharkhand,2961,8986.0,139,24.0,4.0,NaN,NaN,NaN,57.0,12171
13,Karnataka,56737,16478.0,7212,153.0,44.0,1.0,1.0,NaN,1420.0,82046
14,Kerala,10299,2115.0,2524,43.0,23.0,NaN,1.0,NaN,17.0,15022
15,Ladakh,12,NaN,5484,NaN,NaN,NaN,NaN,NaN,NaN,5496
16,Maharashtra,51149,6155.0,2,30.0,851.0,26.0,1.0,NaN,601.0,58815
17,Manipur,86,443.0,9,1.0,NaN,NaN,NaN,NaN,1.0,540
18,Meghalaya,16,6.0,3,3.0,NaN,NaN,NaN,NaN,NaN,28
19,Mizoram,9,1.0,4,2.0,1.0,NaN,NaN,NaN,3.0,20
20,Nagaland,44,NaN,121,3.0,NaN,1.0,NaN,1.0,1.0,171
21,Odisha,10329,1808.0,75,21.0,NaN,25.0,NaN,1.0,23.0,12282
22,Puducherry,1429,32.0,124,9.0,20.0,NaN,NaN,NaN,NaN,1614
23,Punjab,6408,2878.0,798,35.0,2.0,NaN,NaN,NaN,21.0,10142
24,Rajasthan,23446,29631.0,12,25.0,1.0,NaN,1.0,1.0,24.0,53141
25,Sikkim,1,NaN,2414,1.0,NaN,NaN,NaN,NaN,9.0,2425
26,Tamil Nadu,44302,4470.0,13,1281.0,37.0,NaN,NaN,NaN,193.0,50296
27,Tripura,67,7510.0,14,1.0,NaN,NaN,NaN,NaN,1.0,7593
28,Dadra and Nagar Haveli and Daman and Diu,69,36.0,153,2.0,10.0,7.0,NaN,NaN,NaN,277
29,Uttar Pradesh,18295,257159.0,368,53.0,327.0,2.0,NaN,NaN,13.0,276217
30,Uttarakhand,2614,22096.0,709,1.0,10.0,NaN,NaN,NaN,21.0,25451
31,West Bengal,2540,40948.0,615,28.0,97.0,NaN,2.0,NaN,61.0,44291
32,Grand Total,282542,647186.0,26335,3036.0,2039.0,410.0,6.0,397.0,4412.0,966363

In [10]:
df_bikes=pd.read_csv("Vehicle info/ev_model_spec (1).csv")

In [11]:
df_bikes['Type']='Two Wheeler'

In [12]:
df_bikes

,Model Name,Price,Riding Range (km),Top Speed (kmph),Weight (kg),Battery Charging Time (hrs),Rated Power (W),Type
0,Ampere Magnus EX,104758,121,53,90,7,1200,Two Wheeler
1,Ampere Magnus Pro,66053,45,25,94,10,250,Two Wheeler
2,Ampere REO,61993,45,25,88,10,250,Two Wheeler
3,Ampere Zeal,96544,120,53,80,7,1200,Two Wheeler
4,Ather 450X,135489,111,90,108,8,3000,Two Wheeler
5,Bajaj Chetak,131196,90,63,133,5,3800,Two Wheeler
6,Benling Aura,91667,120,60,66,6,2500,Two Wheeler
7,BGauss B8,62999,70,50,99,8,800,Two Wheeler
8,Bounce Infinity E1,100905,85,65,94,4,1500,Two Wheeler
9,e-bike Gen Nxt,74273,60,25,67,4,250,Two Wheeler
10,Evolet Polo,55799,90,25,76,4,250,Two Wheeler
11,Gemopai Astrid Lite,92289,90,65,95,4,2400,Two Wheeler
12,Gemopai Ryder,70821,90,25,80,4,250,Two Wheeler
13,Hero Electric Atria,77767,85,25,69,5,250,Two Wheeler
14,Hero Electric Flash,59594,85,25,69,5,250,Two Wheeler
15,Hero Electric NYX,86490,138,42,87,5,600,Two Wheeler
16,Hero Electric NYX HX,86490,138,42,87,5,600,Two Wheeler
17,Hero Electric Optima,106740,89,48,93,5,1200,Two Wheeler
18,Hero Electric Optima CX,106740,89,48,93,5,1200,Two Wheeler
19,Hero Electric Photon,110376,108,45,87,5,1200,Two Wheeler
20,Joy e-bike Monster,100500,75,25,93,5,250,Two Wheeler
21,Joy e-bike Wolf,78466,60,25,67,4,250,Two Wheeler
22,Odysse Evoqis,171250,140,80,150,6,3000,Two Wheeler
23,Okinawa i-Praise,124872,139,58,150,5,1000,Two Wheeler
24,Okinawa Lite,67006,60,25,150,5,250,Two Wheeler
25,Okinawa Praise,90282,88,58,150,3,1000,Two Wheeler
26,Okinawa R30,61534,60,25,150,5,250,Two Wheeler
27,Okinawa Ridge Plus,73124,84,45,150,3,800,Two Wheeler
28,OLA S1,119827,151,90,108,5,2700,Two Wheeler
29,OLA S1 Pro,139828,170,116,125,7,5500,Two Wheeler
30,PURE EV EPluto 7G,83897,120,60,76,4,1500,Two Wheeler
31,PURE EV ETrance Neo,78999,120,60,86,4,1500,Two Wheeler
32,Revolt RV 300,109242,150,65,101,4,1500,Two Wheeler
33,Revolt RV 400,134975,150,85,108,5,3000,Two Wheeler
34,Techo Electra Emerge,68286,60,25,60,5,250,Two Wheeler
35,Techo Electra Raptor,57893,90,25,60,5,250,Two Wheeler
36,Tork Kratos,167844,180,70,140,7,4000,Two Wheeler
37,TVS iQube,137890,100,78,117,5,3000,Two Wheeler
38,Yo Drift,51094,60,25,59,8,250,Two Wheeler

In [13]:
extraction=list(df.loc[:,'Hyperlink'])
extraction

['https://www.cartrade.com//tata-cars/punch-ev/',
 'https://www.cartrade.com//mg-cars/comet-ev/',
 'https://www.cartrade.com//tata-cars/nexon-ev/',
 'https://www.cartrade.com//tata-cars/tiago-ev/',
 'https://www.cartrade.com//byd-cars/seal/',
 'https://www.cartrade.com//mahindra-cars/xuv400/',
 'https://www.cartrade.com//audi-cars/e-tron-gt/',
 'https://www.cartrade.com//jaguar-cars/i-pace/',
 'https://www.cartrade.com//kia-cars/ev6/',
 'https://www.cartrade.com//hyundai-cars/ioniq-5/',
 'https://www.cartrade.com//byd-cars/atto-3/',
 'https://www.cartrade.com//volvo-cars/xc40-recharge/',
 'https://www.cartrade.com//byd-cars/e6/',
 'https://www.cartrade.com//mg-cars/zs-ev/',
 'https://www.cartrade.com//bmw-cars/i7/',
 'https://www.cartrade.com//bmw-cars/i4/',
 'https://www.cartrade.com//mini-cars/cooper-se/',
 'https://www.cartrade.com//rolls-royce-cars/spectre/',
 'https://www.cartrade.com//volvo-cars/c40-recharge/',
 'https://www.cartrade.com//porsche-cars/taycan/']

In [14]:
cars_n_dataset={'model_name':[]}

In [15]:
for url in extraction:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    model_name = soup.find('h1', class_="model-overview-title font-muli-bold").text
    cars_n_dataset['model_name'].append(model_name)

In [16]:
cars_dataset=[]
for url in extraction:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the table containing the desired information
    table = soup.find('table', class_='keySpecsTable')
    if table:
        # Initialize dictionary to store data for this car
        car_data = {}
        
        # Loop through each row in the table
        for row in table.find_all('tr'):
            # Extract label and value from each row
            label = row.find('th').text.strip()
            value = row.find('td').text.strip()
            
            # Store data in the car_data dictionary
            car_data[label] = value
        
        # Append car_data to cars_dataset
        cars_dataset.append(car_data)

In [17]:
df_cars=pd.DataFrame(cars_dataset)

In [18]:
df_cars.insert(loc=0,column='Name',value=cars_n_dataset['model_name'])

In [19]:
df_cars

,Name,Price,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Warranty,Battery Warranty,Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period,Charging time at home
0,Tata Punch EV,₹ 10.99 - 15.49 Lakh,Electric,315 km,5 People,Not Tested star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,25 kWh,3857 mm L X 1742 mm W X 1633 mm H,190 mm,0 - 27 Weeks,NaN
1,MG Comet EV,₹ 6.99 - 9.24 Lakh,Electric,230 km,4 People,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 120000 km,17.3 kWh,2974 mm L X 1505 mm W X 1640 mm H,NaN,1 - 2 Weeks,NaN
2,Tata Nexon EV,₹ 14.49 - 19.49 Lakh,Electric,325 km,5 People,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,30 kWh,3994 mm L X 1811 mm W X 1616 mm H,205 mm,0 - 16 Weeks,NaN
3,Tata Tiago EV,₹ 7.99 - 11.89 Lakh,Electric,250 km,5 People,4 Star (Global NCAP) star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,19.2 kWh,3769 mm L X 1677 mm W X 1536 mm H,NaN,0 - 14 Weeks,NaN
4,BYD Seal,₹ 41.00 - 53.00 Lakh,Electric,510 km,5 People,5 Star (Euro NCAP) star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,61.44 kWh,4800 mm L X 1875 mm W X 1460 mm H,145 mm,NaN,NaN
5,Mahindra XUV400,₹ 15.49 - 17.69 Lakh,Electric,375 km,5 People,Not Tested star NCAP Rating,3 Years (Unlimited KMs),8 Years (Unlimited KMs),34.5 kWh,4200 mm L X 1821 mm W X 1634 mm H,NaN,2 - 8 Weeks,NaN
6,Audi e-tron GT,₹ 1.72 - 1.95 Crore,Electric,388 km,5 People,5 Star (Euro NCAP) star NCAP Rating,2 Years (Unlimited KMs),8 Years or 160000 km,93.4 kWh,4989 mm L X 1964 mm W X 1418 mm H,NaN,0 - 17 Weeks,NaN
7,Jaguar I-Pace,₹ 1.26 Crore,Electric,470 km,5 People,5 Star (Euro NCAP) star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,90 kWh,4682 mm L X 2139 mm W X 1566 mm H,174 mm,0 - 52 Weeks,NaN
8,Kia EV6,₹ 60.97 - 65.97 Lakh,Electric,708 km,5 People,5 Star (Euro NCAP) star NCAP Rating,NaN,8 Years or 160000 km,77.4 kWh,4695 mm L X 1890 mm W X 1570 mm H,178 mm,0 - 18 Weeks,NaN
9,Hyundai Ioniq 5,₹ 46.05 Lakh,Electric,631 km,5 People,5 Star (Euro NCAP) star NCAP Rating,3 Years or Unlimted km,8 Years or 160000 km,72.6 kWh,4635 mm L X 1890 mm W X 1625 mm H,163 mm,0 - 13 Weeks,NaN
10,BYD Atto 3,₹ 33.99 - 34.49 Lakh,Electric,521 km,5 People,Not Tested star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,60.48 kWh,4455 mm L X 1875 mm W X 1615 mm H,175 mm,NaN,NaN
11,Volvo XC40 Recharge,₹ 54.95 - 57.90 Lakh,Electric,475 km,5 People,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years (Unlimited KMs),69 kWh,4440 mm L X 1863 mm W X 1647 mm H,175 mm,0 - 43 Weeks,NaN
12,BYD e6,₹ 29.15 Lakh,Electric,415 km,5 People,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 500000 km,71.7 kWh,4695 mm L X 1810 mm W X 1670 mm H,170 mm,NaN,NaN
13,MG ZS EV,₹ 18.98 - 25.20 Lakh,Electric,461 km,5 People,5 Star (Euro NCAP) star NCAP Rating,5 Years (Unlimited KMs),8 Years or 150000 km,50.3 kWh,4323 mm L X 1809 mm W X 1649 mm H,NaN,4 - 9 Weeks,16 hours @ 230V
14,BMW i7,₹ 2.13 - 2.50 Crore,Electric,625 km,5 People,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,101.7 kWh,5391 mm L X 1950 mm W X 1544 mm H,NaN,0 - 17 Weeks,52 hours @ 230V
15,BMW i4,₹ 72.50 - 77.50 Lakh,Electric,483 km,5 People,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,70.2 kWh,4783 mm L X 1852 mm W X 1448 mm H,125 mm,0 - 17 Weeks,NaN
16,MINI Cooper SE,₹ 53.00 - 55.00 Lakh,Electric,270 km,4 People,Not Tested star NCAP Rating,2 Years (Unlimited KMs),8 Years or 100000 km,32.6 kWh,3850 mm L X 1727 mm W X 1432 mm H,NaN,NaN,NaN
17,Rolls-Royce Spectre,₹ 7.50 Crore,Electric,530 km,4 People,Not Tested star NCAP Rating,4 Years (Unlimited KMs),No Years or No km,102 kWh,5475 mm L X 2017 mm W X 1573 mm H,NaN,NaN,NaN
18,Volvo C40 Recharge,₹ 62.95 Lakh,Electric,530 km,5 People,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years or 160000 km,78 kWh,4440 mm L X 1873 mm W X 1591 mm H,171 mm,0 - 15 Weeks,NaN
19,Porsche Taycan,₹ 1.61 - 2.44 Crore,Electric,302 km,5 People,Not Tested star NCAP Rating,3 Years or 60000 km,8 Years or 160000 km,79.2 kWh,4963 mm L X 2144 mm W X 1395 mm H,127 mm,NaN,8 hours @ 230V

In [20]:

def extract_top_end_price(price_range):
    try:
        return float(price_range.split(" - ")[1].split(" ")[0])
    except (ValueError, IndexError):
        return None


df_cars['Top End Price (₹)'] = df_cars['Price'].apply(extract_top_end_price)

In [21]:
df_cars.drop(columns=['Price','Charging time at home'],inplace=True)

In [22]:
df_cars['Seating Capacity']=df_cars['Seating Capacity'].apply(lambda x:int(x[0]))
df_cars['Driving Range (km)']=df_cars['Driving Range (km)'].apply(lambda x:int(x[:3]))
df_cars['Battery Capacity']=df_cars['Battery Capacity'].apply(lambda x:float(x[:-3]))

In [23]:
df_cars

,Name,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Warranty,Battery Warranty,Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period,Top End Price (₹)
0,Tata Punch EV,Electric,315,5,Not Tested star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,25.00,3857 mm L X 1742 mm W X 1633 mm H,190 mm,0 - 27 Weeks,15.49
1,MG Comet EV,Electric,230,4,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 120000 km,17.30,2974 mm L X 1505 mm W X 1640 mm H,NaN,1 - 2 Weeks,9.24
2,Tata Nexon EV,Electric,325,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,30.00,3994 mm L X 1811 mm W X 1616 mm H,205 mm,0 - 16 Weeks,19.49
3,Tata Tiago EV,Electric,250,5,4 Star (Global NCAP) star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,19.20,3769 mm L X 1677 mm W X 1536 mm H,NaN,0 - 14 Weeks,11.89
4,BYD Seal,Electric,510,5,5 Star (Euro NCAP) star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,61.44,4800 mm L X 1875 mm W X 1460 mm H,145 mm,NaN,53.00
5,Mahindra XUV400,Electric,375,5,Not Tested star NCAP Rating,3 Years (Unlimited KMs),8 Years (Unlimited KMs),34.50,4200 mm L X 1821 mm W X 1634 mm H,NaN,2 - 8 Weeks,17.69
6,Audi e-tron GT,Electric,388,5,5 Star (Euro NCAP) star NCAP Rating,2 Years (Unlimited KMs),8 Years or 160000 km,93.40,4989 mm L X 1964 mm W X 1418 mm H,NaN,0 - 17 Weeks,1.95
7,Jaguar I-Pace,Electric,470,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,90.00,4682 mm L X 2139 mm W X 1566 mm H,174 mm,0 - 52 Weeks,NaN
8,Kia EV6,Electric,708,5,5 Star (Euro NCAP) star NCAP Rating,NaN,8 Years or 160000 km,77.40,4695 mm L X 1890 mm W X 1570 mm H,178 mm,0 - 18 Weeks,65.97
9,Hyundai Ioniq 5,Electric,631,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Unlimted km,8 Years or 160000 km,72.60,4635 mm L X 1890 mm W X 1625 mm H,163 mm,0 - 13 Weeks,NaN
10,BYD Atto 3,Electric,521,5,Not Tested star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,60.48,4455 mm L X 1875 mm W X 1615 mm H,175 mm,NaN,34.49
11,Volvo XC40 Recharge,Electric,475,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years (Unlimited KMs),69.00,4440 mm L X 1863 mm W X 1647 mm H,175 mm,0 - 43 Weeks,57.90
12,BYD e6,Electric,415,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 500000 km,71.70,4695 mm L X 1810 mm W X 1670 mm H,170 mm,NaN,NaN
13,MG ZS EV,Electric,461,5,5 Star (Euro NCAP) star NCAP Rating,5 Years (Unlimited KMs),8 Years or 150000 km,50.30,4323 mm L X 1809 mm W X 1649 mm H,NaN,4 - 9 Weeks,25.20
14,BMW i7,Electric,625,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,101.70,5391 mm L X 1950 mm W X 1544 mm H,NaN,0 - 17 Weeks,2.50
15,BMW i4,Electric,483,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,70.20,4783 mm L X 1852 mm W X 1448 mm H,125 mm,0 - 17 Weeks,77.50
16,MINI Cooper SE,Electric,270,4,Not Tested star NCAP Rating,2 Years (Unlimited KMs),8 Years or 100000 km,32.60,3850 mm L X 1727 mm W X 1432 mm H,NaN,NaN,55.00
17,Rolls-Royce Spectre,Electric,530,4,Not Tested star NCAP Rating,4 Years (Unlimited KMs),No Years or No km,102.00,5475 mm L X 2017 mm W X 1573 mm H,NaN,NaN,NaN
18,Volvo C40 Recharge,Electric,530,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years or 160000 km,78.00,4440 mm L X 1873 mm W X 1591 mm H,171 mm,0 - 15 Weeks,NaN
19,Porsche Taycan,Electric,302,5,Not Tested star NCAP Rating,3 Years or 60000 km,8 Years or 160000 km,79.20,4963 mm L X 2144 mm W X 1395 mm H,127 mm,NaN,2.44

In [24]:
list(df_cars['Name'].values)

['Tata Punch EV',
 'MG Comet EV',
 'Tata Nexon EV',
 'Tata Tiago EV',
 'BYD Seal',
 'Mahindra XUV400',
 'Audi e-tron GT',
 'Jaguar I-Pace',
 'Kia EV6',
 'Hyundai Ioniq 5',
 'BYD Atto 3',
 'Volvo XC40 Recharge',
 'BYD e6',
 'MG ZS EV',
 'BMW i7',
 'BMW i4',
 'MINI Cooper SE',
 'Rolls-Royce Spectre',
 'Volvo C40 Recharge',
 'Porsche Taycan']

In [25]:
search_urls = []
for model in df_cars['Name']:
    stripped_model = model.replace(' ', '%20')  # Replace spaces with %20 for URL encoding
    url = 'https://auto.hindustantimes.com/search?text=' + stripped_model
    search_urls.append(url)

print(search_urls)

['https://auto.hindustantimes.com/search?text=Tata%20Punch%20EV', 'https://auto.hindustantimes.com/search?text=MG%20Comet%20EV', 'https://auto.hindustantimes.com/search?text=Tata%20Nexon%20EV', 'https://auto.hindustantimes.com/search?text=Tata%20Tiago%20EV', 'https://auto.hindustantimes.com/search?text=BYD%20Seal', 'https://auto.hindustantimes.com/search?text=Mahindra%20XUV400', 'https://auto.hindustantimes.com/search?text=Audi%20e-tron%20GT', 'https://auto.hindustantimes.com/search?text=Jaguar%20I-Pace', 'https://auto.hindustantimes.com/search?text=Kia%20EV6', 'https://auto.hindustantimes.com/search?text=Hyundai%20Ioniq%205', 'https://auto.hindustantimes.com/search?text=BYD%20Atto%203', 'https://auto.hindustantimes.com/search?text=Volvo%20XC40%20Recharge', 'https://auto.hindustantimes.com/search?text=BYD%20e6', 'https://auto.hindustantimes.com/search?text=MG%20ZS%20EV', 'https://auto.hindustantimes.com/search?text=BMW%20i7', 'https://auto.hindustantimes.com/search?text=BMW%20i4', 'https://auto.hindustantimes.com/search?text=MINI%20Cooper%20SE', 'https://auto.hindustantimes.com/search?text=Rolls-Royce%20Spectre', 'https://auto.hindustantimes.com/search?text=Volvo%20C40%20Recharge', 'https://auto.hindustantimes.com/search?text=Porsche%20Taycan']

In [26]:
hlinks=[]
for searches in search_urls:
    response = requests.get(searches)
    soup=BeautifulSoup(response.text,'html.parser')
    finding_hlink=soup.find('a',class_='parentWrapper')
    href=finding_hlink.get('href')
    hlinks.append(href)

In [27]:
hlinks

['https://auto.hindustantimes.com/new-cars/tata/punchev',
 'https://auto.hindustantimes.com/new-cars/mg/cometev',
 'https://auto.hindustantimes.com/new-cars/tata/nexon-ev',
 'https://auto.hindustantimes.com/new-cars/tata/tiagoev',
 'https://auto.hindustantimes.com/new-cars/byd/seal',
 'https://auto.hindustantimes.com/new-cars/mahindra/xuv400ev',
 'https://auto.hindustantimes.com/new-cars/audi/etrongt',
 'https://auto.hindustantimes.com/new-cars/jaguar/ipace',
 'https://auto.hindustantimes.com/new-cars/kia/ev6',
 'https://auto.hindustantimes.com/new-cars/hyundai/ioniq5',
 'https://auto.hindustantimes.com/new-cars/byd/atto3',
 'https://auto.hindustantimes.com/new-cars/volvo/xc40recharge',
 'https://auto.hindustantimes.com/new-cars/byd/e6',
 'https://auto.hindustantimes.com/new-cars/mg/zsev',
 'https://auto.hindustantimes.com/new-cars/bmw/i7',
 'https://auto.hindustantimes.com/new-cars/bmw/i4',
 'https://auto.hindustantimes.com/new-cars/mini/cooper-se-2024',
 'https://auto.hindustantimes.com/new-cars/rollsroyce/spectre',
 'https://auto.hindustantimes.com/new-cars/volvo/c40-recharge',
 'https://auto.hindustantimes.com/new-cars/porsche/taycan']

In [28]:
# Construct the search query
top_speeds=[]
for url in hlinks:

    # Send request to the URL
    response = requests.get(url)

        # Parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')

        # Find the table containing key specifications
    specs_table = soup.find('table', class_='KeySpecs_KeySpecsSectionWrapper__F_3hc')

        # Check if the specs table is found
    if specs_table:
            # Find all rows in the table
        rows = specs_table.find_all('tr')

            # Loop through each row to find the top speed
        for row in rows:
                # Check if the row contains the key 'Top Speed'
            if 'Max Speed' in row.text:
                    # Extract the top speed value from the next row
                top_speed_element = row.find_next('td', class_='KeySpecs_KeySpecsSubtitle__X0vwC')
                top_speed = top_speed_element.get_text(strip=True)
                top_speeds.append(top_speed)

In [29]:
len(hlinks)

20

In [30]:
df_cars['Name']

0           Tata Punch EV
1             MG Comet EV
2           Tata Nexon EV
3           Tata Tiago EV
4                BYD Seal
5         Mahindra XUV400
6          Audi e-tron GT
7           Jaguar I-Pace
8                 Kia EV6
9         Hyundai Ioniq 5
10             BYD Atto 3
11    Volvo XC40 Recharge
12                 BYD e6
13               MG ZS EV
14                 BMW i7
15                 BMW i4
16         MINI Cooper SE
17    Rolls-Royce Spectre
18     Volvo C40 Recharge
19         Porsche Taycan
Name: Name, dtype: object

In [31]:
top_speeds.append('230 Kmph') 
df_cars['Top Speed']=top_speeds

In [32]:
df_cars['Top Speed']=df_cars['Top Speed'].apply(lambda x:int(x[:3]))
df_cars['Top Speed']

0      85
1     100
2     140
3     120
4     180
5     150
6     245
7     200
8     192
9     185
10    160
11    180
12    130
13    140
14    250
15    250
16    250
17    180
18    260
19    230
Name: Top Speed, dtype: int64

In [33]:
import numpy as np
missing_ground_clearance = pd.isna(df_cars['Ground Clearance (mm)'])

In [34]:
list(df_cars[missing_ground_clearance]['Name'].values)

['MG Comet EV',
 'Tata Tiago EV',
 'Mahindra XUV400',
 'Audi e-tron GT',
 'MG ZS EV',
 'BMW i7',
 'MINI Cooper SE',
 'Rolls-Royce Spectre']

In [35]:
ground_clearence=[]
for i in list(df_cars[missing_ground_clearance]['Name'].values):
    gound_clearance_search=f"https://www.google.com/search?q={i.replace(' ','+')}+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp"
    ground_clearence.append(gound_clearance_search)

In [36]:
ground_clearence

['https://www.google.com/search?q=MG+Comet+EV+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=Tata+Tiago+EV+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=Mahindra+XUV400+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=Audi+e-tron+GT+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=MG+ZS+EV+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=BMW+i7+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=MINI+Cooper+SE+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp',
 'https://www.google.com/search?q=Rolls-Royce+Spectre+ground+clearance&sca_esv=39a203f7e53a9de7&sca_upv=1&sxsrf=ACQVn09SOF4oa3cllnKVQVVvtrLt9v7niQ%3A1714451523993&ei=Q3QwZqavPK-5seMPr_C94A4&ved=0ahUKEwjm3MnQjemFAxWvXGwGHS94D-wQ4dUDCBA&uact=5&oq=Audi+e-tron+GT+ground+clearance&gs_lp=Egxnd3Mtd2l6LXNlcnAiH0F1ZGkgZS10cm9uIEdUIGdyb3VuZCBjbGVhcmFuY2UyBRAAGIAEMgYQABgHGB4yBBAAGB4yBhAAGAUYHjILEAAYgAQYhgMYigUyCxAAGIAEGIYDGIoFMggQABiABBiiBDIIEAAYgAQYogRIpZsBUKcGWNWTAXABeAKQAQCYAe8BoAGABKoBBTAuMi4xuAEDyAEA-AEB-AECmAIFoAKpBMICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIEEAAYR8ICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICChAAGIAEGEMYigWYAwDiAwUSATEgQIgGAZAGCJIHBTIuMi4xoAfdEg&sclient=gws-wiz-serp']

In [37]:
ground_clearances=[]
for searches in ground_clearence:
    response = requests.get(searches)
    soup=BeautifulSoup(response.text,'html.parser')
    res=soup.find('span',class_='FCUp0c rQMQod')
    ground_clearances.append(res.text)

In [38]:
ground_clearances

['165 mm',
 '166mm',
 '200 mm',
 '152–248 mm',
 '177 mm',
 '136 mm',
 'People also ask',
 'People also ask']

In [39]:
df_cars[df_cars['Ground Clearance (mm)'].isna()]['Ground Clearance (mm)']=ground_clearances

/tmp/ipykernel_8492/3874711641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cars[df_cars['Ground Clearance (mm)'].isna()]['Ground Clearance (mm)']=ground_clearances

In [40]:
null_indices = df_cars[df_cars['Ground Clearance (mm)'].isnull()].index
df_cars.loc[null_indices, 'Ground Clearance (mm)'] = ground_clearances

In [41]:
df_cars

,Name,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Warranty,Battery Warranty,Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period,Top End Price (₹),Top Speed
0,Tata Punch EV,Electric,315,5,Not Tested star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,25.00,3857 mm L X 1742 mm W X 1633 mm H,190 mm,0 - 27 Weeks,15.49,85
1,MG Comet EV,Electric,230,4,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 120000 km,17.30,2974 mm L X 1505 mm W X 1640 mm H,165 mm,1 - 2 Weeks,9.24,100
2,Tata Nexon EV,Electric,325,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,30.00,3994 mm L X 1811 mm W X 1616 mm H,205 mm,0 - 16 Weeks,19.49,140
3,Tata Tiago EV,Electric,250,5,4 Star (Global NCAP) star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,19.20,3769 mm L X 1677 mm W X 1536 mm H,166mm,0 - 14 Weeks,11.89,120
4,BYD Seal,Electric,510,5,5 Star (Euro NCAP) star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,61.44,4800 mm L X 1875 mm W X 1460 mm H,145 mm,NaN,53.00,180
5,Mahindra XUV400,Electric,375,5,Not Tested star NCAP Rating,3 Years (Unlimited KMs),8 Years (Unlimited KMs),34.50,4200 mm L X 1821 mm W X 1634 mm H,200 mm,2 - 8 Weeks,17.69,150
6,Audi e-tron GT,Electric,388,5,5 Star (Euro NCAP) star NCAP Rating,2 Years (Unlimited KMs),8 Years or 160000 km,93.40,4989 mm L X 1964 mm W X 1418 mm H,152–248 mm,0 - 17 Weeks,1.95,245
7,Jaguar I-Pace,Electric,470,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,90.00,4682 mm L X 2139 mm W X 1566 mm H,174 mm,0 - 52 Weeks,NaN,200
8,Kia EV6,Electric,708,5,5 Star (Euro NCAP) star NCAP Rating,NaN,8 Years or 160000 km,77.40,4695 mm L X 1890 mm W X 1570 mm H,178 mm,0 - 18 Weeks,65.97,192
9,Hyundai Ioniq 5,Electric,631,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Unlimted km,8 Years or 160000 km,72.60,4635 mm L X 1890 mm W X 1625 mm H,163 mm,0 - 13 Weeks,NaN,185
10,BYD Atto 3,Electric,521,5,Not Tested star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,60.48,4455 mm L X 1875 mm W X 1615 mm H,175 mm,NaN,34.49,160
11,Volvo XC40 Recharge,Electric,475,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years (Unlimited KMs),69.00,4440 mm L X 1863 mm W X 1647 mm H,175 mm,0 - 43 Weeks,57.90,180
12,BYD e6,Electric,415,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 500000 km,71.70,4695 mm L X 1810 mm W X 1670 mm H,170 mm,NaN,NaN,130
13,MG ZS EV,Electric,461,5,5 Star (Euro NCAP) star NCAP Rating,5 Years (Unlimited KMs),8 Years or 150000 km,50.30,4323 mm L X 1809 mm W X 1649 mm H,177 mm,4 - 9 Weeks,25.20,140
14,BMW i7,Electric,625,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,101.70,5391 mm L X 1950 mm W X 1544 mm H,136 mm,0 - 17 Weeks,2.50,250
15,BMW i4,Electric,483,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,70.20,4783 mm L X 1852 mm W X 1448 mm H,125 mm,0 - 17 Weeks,77.50,250
16,MINI Cooper SE,Electric,270,4,Not Tested star NCAP Rating,2 Years (Unlimited KMs),8 Years or 100000 km,32.60,3850 mm L X 1727 mm W X 1432 mm H,People also ask,NaN,55.00,250
17,Rolls-Royce Spectre,Electric,530,4,Not Tested star NCAP Rating,4 Years (Unlimited KMs),No Years or No km,102.00,5475 mm L X 2017 mm W X 1573 mm H,People also ask,NaN,NaN,180
18,Volvo C40 Recharge,Electric,530,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years or 160000 km,78.00,4440 mm L X 1873 mm W X 1591 mm H,171 mm,0 - 15 Weeks,NaN,260
19,Porsche Taycan,Electric,302,5,Not Tested star NCAP Rating,3 Years or 60000 km,8 Years or 160000 km,79.20,4963 mm L X 2144 mm W X 1395 mm H,127 mm,NaN,2.44,230

In [42]:
df_cars[df_cars['Ground Clearance (mm)']=='People also ask']['Ground Clearance(mm)']=['142mm','125mm']

/tmp/ipykernel_8492/889814370.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cars[df_cars['Ground Clearance (mm)']=='People also ask']['Ground Clearance(mm)']=['142mm','125mm']

In [43]:
replacing_values_index = df_cars[df_cars['Ground Clearance (mm)']=='People also ask'].index
df_cars.loc[replacing_values_index, 'Ground Clearance (mm)'] = ['146mm','150mm']

In [44]:
df_cars['Ground Clearance (mm)'] = df_cars['Ground Clearance (mm)'].apply(lambda x:int(x[:3]))
df_cars['Ground Clearance (mm)']

0     190
1     165
2     205
3     166
4     145
5     200
6     152
7     174
8     178
9     163
10    175
11    175
12    170
13    177
14    136
15    125
16    146
17    150
18    171
19    127
Name: Ground Clearance (mm), dtype: int64

In [45]:
df_cars

,Name,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Warranty,Battery Warranty,Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period,Top End Price (₹),Top Speed
0,Tata Punch EV,Electric,315,5,Not Tested star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,25.00,3857 mm L X 1742 mm W X 1633 mm H,190,0 - 27 Weeks,15.49,85
1,MG Comet EV,Electric,230,4,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 120000 km,17.30,2974 mm L X 1505 mm W X 1640 mm H,165,1 - 2 Weeks,9.24,100
2,Tata Nexon EV,Electric,325,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,30.00,3994 mm L X 1811 mm W X 1616 mm H,205,0 - 16 Weeks,19.49,140
3,Tata Tiago EV,Electric,250,5,4 Star (Global NCAP) star NCAP Rating,3 Years or 125000 km,8 Years or 160000 km,19.20,3769 mm L X 1677 mm W X 1536 mm H,166,0 - 14 Weeks,11.89,120
4,BYD Seal,Electric,510,5,5 Star (Euro NCAP) star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,61.44,4800 mm L X 1875 mm W X 1460 mm H,145,NaN,53.00,180
5,Mahindra XUV400,Electric,375,5,Not Tested star NCAP Rating,3 Years (Unlimited KMs),8 Years (Unlimited KMs),34.50,4200 mm L X 1821 mm W X 1634 mm H,200,2 - 8 Weeks,17.69,150
6,Audi e-tron GT,Electric,388,5,5 Star (Euro NCAP) star NCAP Rating,2 Years (Unlimited KMs),8 Years or 160000 km,93.40,4989 mm L X 1964 mm W X 1418 mm H,152,0 - 17 Weeks,1.95,245
7,Jaguar I-Pace,Electric,470,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or 100000 km,8 Years or 160000 km,90.00,4682 mm L X 2139 mm W X 1566 mm H,174,0 - 52 Weeks,NaN,200
8,Kia EV6,Electric,708,5,5 Star (Euro NCAP) star NCAP Rating,NaN,8 Years or 160000 km,77.40,4695 mm L X 1890 mm W X 1570 mm H,178,0 - 18 Weeks,65.97,192
9,Hyundai Ioniq 5,Electric,631,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Unlimted km,8 Years or 160000 km,72.60,4635 mm L X 1890 mm W X 1625 mm H,163,0 - 13 Weeks,NaN,185
10,BYD Atto 3,Electric,521,5,Not Tested star NCAP Rating,6 Years or 150000 km,8 Years or 160000 km,60.48,4455 mm L X 1875 mm W X 1615 mm H,175,NaN,34.49,160
11,Volvo XC40 Recharge,Electric,475,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years (Unlimited KMs),69.00,4440 mm L X 1863 mm W X 1647 mm H,175,0 - 43 Weeks,57.90,180
12,BYD e6,Electric,415,5,Not Tested star NCAP Rating,3 Years or 125000 km,8 Years or 500000 km,71.70,4695 mm L X 1810 mm W X 1670 mm H,170,NaN,NaN,130
13,MG ZS EV,Electric,461,5,5 Star (Euro NCAP) star NCAP Rating,5 Years (Unlimited KMs),8 Years or 150000 km,50.30,4323 mm L X 1809 mm W X 1649 mm H,177,4 - 9 Weeks,25.20,140
14,BMW i7,Electric,625,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,101.70,5391 mm L X 1950 mm W X 1544 mm H,136,0 - 17 Weeks,2.50,250
15,BMW i4,Electric,483,5,Not Tested star NCAP Rating,No Years or Not Applicable km,8 Years or 160000 km,70.20,4783 mm L X 1852 mm W X 1448 mm H,125,0 - 17 Weeks,77.50,250
16,MINI Cooper SE,Electric,270,4,Not Tested star NCAP Rating,2 Years (Unlimited KMs),8 Years or 100000 km,32.60,3850 mm L X 1727 mm W X 1432 mm H,146,NaN,55.00,250
17,Rolls-Royce Spectre,Electric,530,4,Not Tested star NCAP Rating,4 Years (Unlimited KMs),No Years or No km,102.00,5475 mm L X 2017 mm W X 1573 mm H,150,NaN,NaN,180
18,Volvo C40 Recharge,Electric,530,5,5 Star (Euro NCAP) star NCAP Rating,3 Years or Not Applicable km,8 Years or 160000 km,78.00,4440 mm L X 1873 mm W X 1591 mm H,171,0 - 15 Weeks,NaN,260
19,Porsche Taycan,Electric,302,5,Not Tested star NCAP Rating,3 Years or 60000 km,8 Years or 160000 km,79.20,4963 mm L X 2144 mm W X 1395 mm H,127,NaN,2.44,230

In [46]:
df_cars.shape,df_bikes.shape

((20, 13), (39, 8))

In [48]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
reshaped_column = np.reshape(df_cars['NCAP Rating (Best - 5 Star)'].values, (-1, 1))
reshaped_column
df_cars['NCAP Rating (Best - 5 Star)']=oe.fit_transform(reshaped_column)

In [52]:
df_cars['Warranty']

0              3 Years or 100000 km
1     No Years or Not Applicable km
2              3 Years or 125000 km
3              3 Years or 125000 km
4              6 Years or 150000 km
5           3 Years (Unlimited KMs)
6           2 Years (Unlimited KMs)
7              3 Years or 100000 km
8                               NaN
9            3 Years or Unlimted km
10             6 Years or 150000 km
11     3 Years or Not Applicable km
12             3 Years or 125000 km
13          5 Years (Unlimited KMs)
14    No Years or Not Applicable km
15    No Years or Not Applicable km
16          2 Years (Unlimited KMs)
17          4 Years (Unlimited KMs)
18     3 Years or Not Applicable km
19              3 Years or 60000 km
Name: Warranty, dtype: object

In [58]:
replacing_values_index = df_cars[df_cars['Warranty'].isnull()].index
df_cars.loc[replacing_values_index, 'Warranty'] = ['3 Years or unlimited km']

In [64]:
# Find the indices where 'Warranty' is 'No Years or Not Applicable km'
replacing_values_index = df_cars[df_cars['Warranty'] == 'No Years or Not Applicable km'].index

# Create a list of warranties with the same length as replacing_values_index
warranties = ['3 years or 100000 km', '4 years or 80000 km', '4 years or 80000 km'] 
# Update the 'Warranty' column for the corresponding indices
df_cars.loc[replacing_values_index, 'Warranty'] = warranties

In [68]:
df_cars['Warranty (Years)']=df_cars['Warranty'].apply(lambda x:int(x[0]))
df_cars['Warranty']

0             3 Years or 100000 km
1             3 years or 100000 km
2             3 Years or 125000 km
3             3 Years or 125000 km
4             6 Years or 150000 km
5          3 Years (Unlimited KMs)
6          2 Years (Unlimited KMs)
7             3 Years or 100000 km
8                3 yr/unlimited km
9           3 Years or Unlimted km
10            6 Years or 150000 km
11    3 Years or Not Applicable km
12            3 Years or 125000 km
13         5 Years (Unlimited KMs)
14             4 years or 80000 km
15             4 years or 80000 km
16         2 Years (Unlimited KMs)
17         4 Years (Unlimited KMs)
18    3 Years or Not Applicable km
19             3 Years or 60000 km
Name: Warranty, dtype: object

In [93]:
extracted_km_values = []
pattern = r'(\d+)\s*km'
for entry in df_cars['Warranty']:
    extracted_data = re.search(pattern, entry, flags=re.IGNORECASE)
    if extracted_data:
        extracted_km_values.append(int(extracted_data.group(1)))
    else:
    
        extracted_km_values.append(100000)  

print(extracted_km_values)

[100000, 100000, 125000, 125000, 150000, 100000, 100000, 100000, 100000, 100000, 150000, 100000, 125000, 100000, 80000, 80000, 100000, 100000, 100000, 60000]

In [94]:
df_cars['Warranty (Km)']=extracted_km_values

In [96]:
df_cars.drop(columns='Warranty',inplace=True)

In [104]:
index_to_change=df_cars[df_cars['Battery Warranty']=='No Years or No km'].index
df_cars.loc[index_to_change,'Battery Warranty']= '10 Years (Unlimited KMs)'

In [106]:
df_cars['Battery Warrenty (yr)']=df_cars['Battery Warranty'].apply(lambda x:int(x[:2]))

In [114]:
extracted_km_values = []
pattern = r'(\d+)\s*km'
for entry in df_cars['Battery Warranty']:
    extracted_data = re.search(pattern, entry, flags=re.IGNORECASE)
    if extracted_data:
        extracted_km_values.append(int(extracted_data.group(1)))
    else:
    
        extracted_km_values.append(100000)  

print(extracted_km_values)
df_cars['Battery Warranty (km)']=extracted_km_values
df_cars.drop(columns='Battery Warranty',inplace=True)

[160000, 120000, 160000, 160000, 160000, 100000, 160000, 160000, 160000, 160000, 160000, 100000, 500000, 150000, 160000, 160000, 100000, 100000, 160000, 160000]

In [122]:
df_cars['Size'].values
volumes = []
for dim in df_cars['Size'].values:
    dim_parts = dim.split(' X ')
    length = float(dim_parts[0].split()[0])
    width = float(dim_parts[1].split()[0])
    height = float(dim_parts[2].split()[0])
    volume = length * width * height
    volumes.append(volume)
df_cars['Size']=volumes

In [123]:
df_cars

,Name,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period,Top End Price (₹),Top Speed,Warranty (Years),Warranty (Km),Battery Warrenty (yr),Battery Warranty (km)
0,Tata Punch EV,Electric,315,5,2.0,25.00,1.097195e+10,190,0 - 27 Weeks,15.49,85,3,100000,8,160000
1,MG Comet EV,Electric,230,4,2.0,17.30,7.340427e+09,165,1 - 2 Weeks,9.24,100,3,100000,8,120000
2,Tata Nexon EV,Electric,325,5,2.0,30.00,1.168874e+10,205,0 - 16 Weeks,19.49,140,3,125000,8,160000
3,Tata Tiago EV,Electric,250,5,0.0,19.20,9.708462e+09,166,0 - 14 Weeks,11.89,120,3,125000,8,160000
4,BYD Seal,Electric,510,5,1.0,61.44,1.314000e+10,145,NaN,53.00,180,6,150000,8,160000
5,Mahindra XUV400,Electric,375,5,2.0,34.50,1.249716e+10,200,2 - 8 Weeks,17.69,150,3,100000,8,100000
6,Audi e-tron GT,Electric,388,5,1.0,93.40,1.389413e+10,152,0 - 17 Weeks,1.95,245,2,100000,8,160000
7,Jaguar I-Pace,Electric,470,5,1.0,90.00,1.568317e+10,174,0 - 52 Weeks,NaN,200,3,100000,8,160000
8,Kia EV6,Electric,708,5,1.0,77.40,1.393147e+10,178,0 - 18 Weeks,65.97,192,3,100000,8,160000
9,Hyundai Ioniq 5,Electric,631,5,1.0,72.60,1.423524e+10,163,0 - 13 Weeks,NaN,185,3,100000,8,160000
10,BYD Atto 3,Electric,521,5,2.0,60.48,1.349030e+10,175,NaN,34.49,160,6,150000,8,160000
11,Volvo XC40 Recharge,Electric,475,5,1.0,69.00,1.362352e+10,175,0 - 43 Weeks,57.90,180,3,100000,8,100000
12,BYD e6,Electric,415,5,2.0,71.70,1.419158e+10,170,NaN,NaN,130,3,125000,8,500000
13,MG ZS EV,Electric,461,5,1.0,50.30,1.289569e+10,177,4 - 9 Weeks,25.20,140,5,100000,8,150000
14,BMW i7,Electric,625,5,2.0,101.70,1.623122e+10,136,0 - 17 Weeks,2.50,250,4,80000,8,160000
15,BMW i4,Electric,483,5,2.0,70.20,1.282655e+10,125,0 - 17 Weeks,77.50,250,4,80000,8,160000
16,MINI Cooper SE,Electric,270,4,2.0,32.60,9.521296e+09,146,NaN,55.00,250,2,100000,8,100000
17,Rolls-Royce Spectre,Electric,530,4,2.0,102.00,1.737076e+10,150,NaN,NaN,180,4,100000,10,100000
18,Volvo C40 Recharge,Electric,530,5,1.0,78.00,1.323095e+10,171,0 - 15 Weeks,NaN,260,3,100000,8,160000
19,Porsche Taycan,Electric,302,5,2.0,79.20,1.484374e+10,127,NaN,2.44,230,3,60000,8,160000

In [124]:
df_cars.isna().sum()

Name                           0
Fuel Type                      0
Driving Range (km)             0
Seating Capacity               0
NCAP Rating (Best - 5 Star)    0
Battery Capacity               0
Size                           0
Ground Clearance (mm)          0
Avg. Waiting Period            6
Top End Price (₹)              5
Top Speed                      0
Warranty (Years)               0
Warranty (Km)                  0
Battery Warrenty (yr)          0
Battery Warranty (km)          0
dtype: int64

In [134]:
list(df_cars[df_cars['Avg. Waiting Period'].isna()].index)

[4, 10, 12, 16, 17, 19]

In [136]:
replacements = {
    'Avg. Waiting Period': ['1 - 12 Weeks', '1-8 Weeks', '1-8 Weeks', '1-16 Weeks', '1-52 Weeks', '1-26 Weeks']
}
df_cars.loc[[4, 10, 12, 16, 17, 19], 'Avg. Waiting Period'] = replacements['Avg. Waiting Period']

In [150]:
df_cars['Avg. Waiting Period'].values
intervals_days = []
for interval in df_cars['Avg. Waiting Period'].values:
    parts = interval.split('-')
    end = int(parts[-1].strip().split()[0]) * 7    # Extract numeric part, convert end of range to days
    intervals_days.append(end)
df_cars['Avg. Waiting Period']=intervals_days

In [156]:
df_cars.rename(columns={'Avg. Waiting Period':'Avg. Waiting Period (Days)'},inplace=True)
df_cars

,Name,Fuel Type,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period (Days),Top End Price (₹),Top Speed,Warranty (Years),Warranty (Km),Battery Warrenty (yr),Battery Warranty (km)
0,Tata Punch EV,Electric,315,5,2.0,25.00,1.097195e+10,190,189,15.49,85,3,100000,8,160000
1,MG Comet EV,Electric,230,4,2.0,17.30,7.340427e+09,165,14,9.24,100,3,100000,8,120000
2,Tata Nexon EV,Electric,325,5,2.0,30.00,1.168874e+10,205,112,19.49,140,3,125000,8,160000
3,Tata Tiago EV,Electric,250,5,0.0,19.20,9.708462e+09,166,98,11.89,120,3,125000,8,160000
4,BYD Seal,Electric,510,5,1.0,61.44,1.314000e+10,145,84,53.00,180,6,150000,8,160000
5,Mahindra XUV400,Electric,375,5,2.0,34.50,1.249716e+10,200,56,17.69,150,3,100000,8,100000
6,Audi e-tron GT,Electric,388,5,1.0,93.40,1.389413e+10,152,119,1.95,245,2,100000,8,160000
7,Jaguar I-Pace,Electric,470,5,1.0,90.00,1.568317e+10,174,364,NaN,200,3,100000,8,160000
8,Kia EV6,Electric,708,5,1.0,77.40,1.393147e+10,178,126,65.97,192,3,100000,8,160000
9,Hyundai Ioniq 5,Electric,631,5,1.0,72.60,1.423524e+10,163,91,NaN,185,3,100000,8,160000
10,BYD Atto 3,Electric,521,5,2.0,60.48,1.349030e+10,175,56,34.49,160,6,150000,8,160000
11,Volvo XC40 Recharge,Electric,475,5,1.0,69.00,1.362352e+10,175,301,57.90,180,3,100000,8,100000
12,BYD e6,Electric,415,5,2.0,71.70,1.419158e+10,170,56,NaN,130,3,125000,8,500000
13,MG ZS EV,Electric,461,5,1.0,50.30,1.289569e+10,177,63,25.20,140,5,100000,8,150000
14,BMW i7,Electric,625,5,2.0,101.70,1.623122e+10,136,119,2.50,250,4,80000,8,160000
15,BMW i4,Electric,483,5,2.0,70.20,1.282655e+10,125,119,77.50,250,4,80000,8,160000
16,MINI Cooper SE,Electric,270,4,2.0,32.60,9.521296e+09,146,112,55.00,250,2,100000,8,100000
17,Rolls-Royce Spectre,Electric,530,4,2.0,102.00,1.737076e+10,150,364,NaN,180,4,100000,10,100000
18,Volvo C40 Recharge,Electric,530,5,1.0,78.00,1.323095e+10,171,105,NaN,260,3,100000,8,160000
19,Porsche Taycan,Electric,302,5,2.0,79.20,1.484374e+10,127,182,2.44,230,3,60000,8,160000

In [162]:
index_cars=df_cars[df_cars['Top End Price (₹)'].isna()].index
df_cars.loc[index_cars,'Top End Price (₹)']=[12600000.0, 4600000.0, 2915000.0, 86000000.0, 6295000.0]

In [168]:
list(df_cars['Top End Price (₹)'])
values_cost=[1549000.0,
 924000.0,
 1949000.0,
 1189000.0,
 5300000.0,
 1769000.0,
 19500000.0,
 12600000.0,
 6597000.0,
 4600000.0,
 3449000.0,
 5790000.0,
 2915000.0,
 252000.0,
 250000.0,
 7750000.0,
 5500000.0,
 86000000.0,
 6295000.0,
 24400000.0]
df_cars['Top End Price (₹)']=values_cost

In [171]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         20 non-null     object
 1   Fuel Type                    20 non-null     object
 2   Driving Range (km)           20 non-null     int64
 3   Seating Capacity             20 non-null     int64
 4   NCAP Rating (Best - 5 Star)  20 non-null     float64
 5   Battery Capacity             20 non-null     float64
 6   Size                         20 non-null     float64
 7   Ground Clearance (mm)        20 non-null     int64
 8   Avg. Waiting Period (Days)   20 non-null     int64
 9   Top End Price (₹)            20 non-null     float64
 10  Top Speed                    20 non-null     int64
 11  Warranty (Years)             20 non-null     int64
 12  Warranty (Km)                20 non-null     int64
 13  Battery Warrenty (yr)        20 non-null     int64
 14  Battery Warranty (km)        20 non-null     int64
dtypes: float64(4), int64(9), object(2)
memory usage: 2.5+ KB

In [172]:
df_cars.describe()

,Driving Range (km),Seating Capacity,NCAP Rating (Best - 5 Star),Battery Capacity,Size,Ground Clearance (mm),Avg. Waiting Period (Days),Top End Price (₹),Top Speed,Warranty (Years),Warranty (Km),Battery Warrenty (yr),Battery Warranty (km)
count,20.00000,20.000000,20.000000,20.000000,2.000000e+01,20.00000,20.000000,2.000000e+01,20.000000,20.000000,20.000000,20.000000,20.000000
mean,440.70000,4.850000,1.500000,61.801000,1.306582e+10,164.50000,136.500000,9.928900e+06,181.350000,3.450000,104750.000000,8.100000,162500.000000
std,133.60275,0.366348,0.606977,27.183588,2.367143e+09,21.93891,98.616482,1.898345e+07,53.499902,1.099043,21550.125168,0.447214,83216.584885
min,230.00000,4.000000,0.000000,17.300000,7.340427e+09,125.00000,14.000000,2.500000e+05,85.000000,2.000000,60000.000000,8.000000,100000.000000
25%,322.50000,5.000000,1.000000,34.025000,1.229506e+10,149.00000,78.750000,1.714000e+06,140.000000,3.000000,100000.000000,8.000000,142500.000000
50%,465.50000,5.000000,2.000000,69.600000,1.336062e+10,168.00000,112.000000,4.950000e+06,180.000000,3.000000,100000.000000,8.000000,160000.000000
75%,523.25000,5.000000,2.000000,78.300000,1.420249e+10,175.50000,140.000000,6.885250e+06,233.750000,4.000000,106250.000000,8.000000,160000.000000
max,708.00000,5.000000,2.000000,102.000000,1.737076e+10,205.00000,364.000000,8.600000e+07,260.000000,6.000000,150000.000000,10.000000,500000.000000

In [174]:
df_cars.to_excel("Indian EV Cars.xlsx")